### ISSUE TITLE
Submit Project 7 - Neighborhood Project

### ISSUE THREAD

**Issue by rudimusmaximus** [rudimusmaximus/FENDp7#1]
**_objective / purpose_**  
Submit project with acceptance  

**_completion checklist_**
**Interface Design**  
  - [x] Responsiveness - All application components render on-screen in a responsive manner.
  - [x] Usability - All application components are usable across modern desktop, tablet, and phone browsers.

**Application Functionality**
  - [x] Location Filter - Includes a text input field or dropdown menu that filters the map markers and list items to locations matching the text input or selection. Filter function runs error-free.
  - [x] List View - A list-view of location names is provided which displays all locations by default, and displays the filtered subset of locations when a filter is applied. Clicking a location on the list displays unique information about the location, and animates its associated map marker (e.g. bouncing, color change.) List functionality is responsive and runs error free.
  - [x] Map and Markers - Map displays all location markers by default, and displays the filtered subset of location markers when a filter is applied. Clicking a marker displays unique information about a location somewhere on the page (modal, separate div, inside an infoWindow). Any additional custom functionality provided in the app functions error-free.  

**Asynchronous Data Usage**
  - [x] Asynchronous API Requests -  Application utilizes the `Google Maps API` or another mapping system and at least one non-Google third-party API. Refer to [this documentation](https://developers.google.com/maps/documentation/javascript/tutorial). All data requests are retrieved in an asynchronous manner using either the `Fetch API` or `XMLHttpRequest`.
  - [x] Error Handling - Data requests that fail are handled gracefully using common fallback techniques (i.e. `AJAX` error or fail methods). 'Gracefully' means the user isn’t left wondering why a component isn’t working. If an `API` doesn’t load there should be some visible indication on the page that it didn’t load.

**Documentation**
  - [x] REAMDE - A `README` file is included detailing all steps required to successfully run the application.
  - [x] Comments - Comments are present and effectively explain longer code procedures.

**Location Details Functionality**
  - [x] Additional Location Data - Functionality providing additional data about a location is provided and sourced from a 3rd party API. Information can be provided either in the marker’s `infoWindow`, or in an `HTML` element in the `DOM` (a sidebar, the list view, a modal, etc.) Provide attribution for the source of additional data. For example, if using Foursquare, indicate somewhere in your UI and in your README that you are using Foursquare data.
  - [x] Error Free - Application runs without console errors.
  - [x] Usability - Functionality is presented in a usable and responsive manner.

**Accessibility**
  - [x] Focus - Focus is appropriately managed allowing users to noticeably tab through each of the important elements of the page. Modal or interstitial windows appropriately lock focus.
  - [x] Site elements are defined semantically - Elements on the page use the appropriate semantic elements. For those elements in which a semantic element is not available, appropriate `ARIA roles` are defined.
  - [x] Accessible Images - All content-related images include appropriate alternate text that clearly describes the content of the image.

**Offline Use**
  - [x] Service Worker - When available in the browser, the site uses a service worker to cache responses to requests for site assets. Visited pages are rendered when there is no network access.  

**Application Architecture**
  - [x] Proper Use of React - React code follows a reasonable component structure. State control is managed appropriately: event handlers are passed as props to child components, and state is managed by parent component functions when appropriate. There are at least 5 locations in the model. These may be hard-coded or retrieved from a data API. There are no errors. There are no warnings that resulted from not following the best practices listed in the documentation, such as using `key` for list items. All code is functional and formatted properly.  

--  
- [x] Developer Tested - Test Copies

POST LIVE:
- [x] Accepted by Udacity reviewer

**_full pipeline documentation_**
---
# Overview - describe with history and related items  
# Solution Design  
Course requirements as included in above checklist [Project Rubric](https://review.udacity.com/#!/rubrics/1351/view)
And in `DESIGN_NOTES` section of `README.md`  

# What's New Entry  
n/a
# Solution Implementation Notes  
 GloBoards from atom:
<img width="2030" alt="screen shot 2018-12-18 at 4 44 59 pm" src="https://user-images.githubusercontent.com/21182598/50187731-99f0b980-02e4-11e9-9020-81ac846a8a14.png">
GloBoard from apple iOS app:
![img_2091](https://user-images.githubusercontent.com/21182598/50187948-82660080-02e5-11e9-8a05-8753aeabac23.PNG)
![img_2092](https://user-images.githubusercontent.com/21182598/50187954-885be180-02e5-11e9-88e1-19fc0bf77d3e.PNG)
![img_2093](https://user-images.githubusercontent.com/21182598/50187960-8eea5900-02e5-11e9-85d2-2523b3d0a030.PNG)

**Comment by rudimusmaximus** [comment]
## working impl notes
### TODO:
```
                      <li>awesome font hamburger with working toggle functionality</li>
                      <li>load the markers using json api and utility functions</li>
                      <li>add the sidebar/menu/collapsible list</li>
                      <li>npm shorid for indexing the jsx elements</li>
                      <li>window popups for markers already done load from api</li>
                      <li>activate service worker and test</li>
```
Overall
 ```
                     <li>rubric checklist in issue 1</li>
                     <li>bonus more info from another api like squarspace</li>
```
Done
```
                      <li>paint the search box or selectable filter</li>
                      <li>paint the map</li>
                      <li>load dfwTips data from api with error handling</li>
                      <li>parse into components as i go</li>
```

**Comment by rudimusmaximus** [comment]
```css
.tempTODO {
  color: #083ca4;
  font-weight: bold;
}

.done {
  font-weight: normal;
}

.tempOl {
  text-align: left;
  font-weight: bold;
}

```

**Comment by rudimusmaximus** [comment]
- [x] Need second submission, see code review. Reviewer requests adding readme section to explain how to run npm install when wishing to setup development for testing on a new machine.
